<<<

== 7.Analyse critique et travaux ultérieur

=== 7.1.Critiquer le travail 

Dans le but d'améliorer la qualité de ce mémoire, j'ai évalué mon travail en établissant une autocritique, qui sera présentée dans ce paragraphe, ainsi que mes pensées pour le future travail en cas si quelqu’un veut poursuivre les résultats issus de mes travaux.
En réfléchissant autour du thème de recherche choisi, le *Green-IT*, j'ai posé, au début, la problématique suivante : *Le logiciel et son cycle de vie font-ils vieillir le matériel plus ou moins rapidement?*.

Cette problématique traite le fait que le logiciel, par son exploitation, fait vieillir l’appareil informatique au sens physique, ce qui le rend bien usé et le met en décharge. 

Mais, pour objectif de mieux contextualiser le sujet de recherche, j'ai reformulé la problématique afin qu'elle soit : *Le logiciel et son cycle de vie provoquent-ils le renouvellement prématuré des terminaux?*. Cela m’a permis de bien structurer mon travail et le plan de recherche, et m’a laissé réfléchir à tous les aspects pertinents, comme celui qui traite si le logiciel, par sa complexité et sa mal conception, raccourcit la durée de vie supposée par le fabricant de l’appareil informatique. 

Une bonne partie du mémoire a été consacrée à établir une matrice permettant aux chefs de projets de tester la durabilité de leurs logiciels. Cette matrice a été fondée sur les résultats issus des interviews avec des experts, ainsi d’un questionnaire publié sur le web via mon réseau professionnel. Ce questionnaire contenait deux types des critères : positifs et négatifs rendant le logiciel plus ou moins durable. Lorsque je construisais la matrice, j’ai trouvé qu’il serait plus adapté si tous les critères ont été posés dans le sens positif, selon le degré de leur positivité par rapport à la durabilité des logiciels. Donc, et par exemple, j’ai reformulé deux critères : l’*Usage intensif du CPU*, et l’*Usage intensif de la mémoire*, posés initialement au sens négatif, afin qu’ils soient posés au sens positif comme les autres critères en leur accordant une note selon leur position par rapport à l’échelle de la durabilité des logiciels.

=== 7.2.Travaux d'avenir

