<<<

== Annexes 

=== Annexe 2 Retranscription interview M. Baptiste LETELLIER

*Qu'entendons-nous par "éco-conception" ?*

Les choses à savoir sur les conceptions :
 
Tu as plus d'impact si tu fais sur le front que sur le back.
Je m'explique: les vrais postes de dépenses en énergie c’est essayer de limiter la consommation d'énergie et d’eau, en fait, optimiser les process algorithmiques.
Cela veut dire que la plupart des règles d'éco-conception ça reviennent à des bonnes pratiques de codes ça, aller simplification, aller au plus rapide avec moins
de ressources.

Mises à part quelques exceptions, globalement, c'est des choses qui sont pratiquement appliquées si tu fais des tests de code bien écrits.

Évidemment, sachant que beaucoup de prestataires ne font pas c'est bonnes pratiques, il peut être bénéfique de mettre en place ces démarches d'éco-conception
pour insister sur le fait que non seulement un code mal écrit, ce n’est pas seulement compréhensible et surtout il gaspille de l'énergie. Donc, étendre de
développement durable à tous phases va bien.

Par contre, c’est pour ça que RTE fait avec les sous-traitants qui se chargent du front, des IHM, des applications web, tu n'as pas trop de règles de conceptions pour des codes back.
 
Autre point de l'éco-conception: identifier là où tu peux gagner le plus. Il y a des tas de façons de faire, de règles.
Pour éviter de se disperser sur l'état de choses , tu vas essayer de trouver des postes de dépenses prioritaires plutôt que de faire un code qui soit parfait.
Tu gagnes plus sur le web et sur les IHM que sur le code java en derrière.

Il y a le livre «Éco-conception web» qui te montre les bonnes pratiques pour construire un site web. Les formations sur Green IT est plus générale (les imprimantes, les data-center et la partie logiciel), toi ce qui t'intéressera c’est la partie logiciel.

Il y pas forcément du JAVA, c’est axé sur le développement web. Il est plus efficace de se focaliser sur la partie web car c’est là que tu feras du gain, que sur la partie back.

Deuxième chose:
 
Il y a beaucoup d'entreprises qui font du Greenwashing, c’est très à la mode ( de dire j'ai fait concevoir un éco-logiciel sans savoir ce qu'ils font).
La plupart du temps, les gens ne savent pas de quoi ils parlent, ils vendent leurs services très chers à des grosses entreprises qui se donnent une image verte.

*Le green IT comment ça marche si je veux l'appliquer ? quel est le critère pour faire un logiciel  plus durable ?* 

Les critères :

Pour avoir un logiciel totalement éco-conçu, tu dois penser en cycle de développement.
Tu dois penser du début à la fin comment tu vas réduire au minimum les ressources nécessaires.

Avant tout ça veux dire: bien penser ton site web: il n'y a pas forcément de critère tout à fait objectif sur comment le construire mais il y a un principe de sobriété générale: aller au plus simple.

Par exemple, on a deux site :

le 1er: ça c'est un site web, tu as des grosses images, des boutons dans tous les sens.
le 2e: ça c'est l'idéal, faire simple, avec le moins d'images possible. 

Tu dois trouver un juste milieu. Un truc simplifier idéalement, le mois images possible.
Il faut faire un bon cahier des charges, tu dois discuter avec le métier pour voir quels sont leurs besoins précis, savoir les freiner.

Donc éco-conception c'est identifier les besoins bruts et virer le superflu.

C'est au fur et à mesure du projet que tu peux mesurer ta performance environnementale et savoir faire un retour (là c'est un logiciel mal conçu, il faut que je recommence).

*Est-ce qu’il y a des outils pour mesurer la performance de site web ?*

Eco-index: pour mesurer la performance. Ensuite, tu compares avec d'autres pages.

c'est une formule qui est calculée à partir du nombre de requête, la taille de la page, de la mémoire et ça te renvoie le CO2, l'eau... pour te donner une note globale. C’est un outil pour la page web. Pour Java, il n'y a pas forcement des outils  pour le tester, encore une fois, la démarche est focalisée plutôt sur le web,  sur les IHM que le java. 

Pour mettre en place une démarche comme ça, cela suppose de préparer énormément, il faut avoir beaucoup d'éléments (avoir déjà une historique, avoir déjà une détaille de projet)  pour comparer les performances, comparer entre ce que tu as fait, l'impact  de ton éco-conception (comment c'était avant et ce que tu as fait les choses nécessaires).
C'est des choses qui demandent beaucoup d'années pour mettre en place.
C'est pas simple du tout, il y a beaucoup d’entreprises qui essaient de faire des sites plus green, mais il faut des critères objectifs, il faut de bon compréhension la démarche, elles essaient de le faire, mais au final, ça ne donne pas de grands choses. C'est bien que de plus en plus de gens s'intéressent au sujet. Au fur à mesure il y a plus de retours pour savoir comment bien faire, et surtout de ne pas faire !

*Il n' y a pas de critères pour savoir s'il est bien ou non ?*

Il y a des critères sur le web. 

*C'est quoi le critère pour le web?*

Eco-index, les équivalents CO2 et la quantité en eau. 
Tu estimes avec la taille de la mémoire, le poids de la page et le nombre de requêtes.

*C'est quoi la relation entre le site web et l’impact environnementale ?*

C'est par la consommation en électricité.
Le Green IT c’est vraiment la démarche en global, il prend tout, de la conception du poste (quand tu construis un ordinateur, tu as besoin de consommation d’énergie, de l’eau pour les matières) en suite, lors de la phase d’utilisation du poste (ça consomme l’électricité et de l’eau). Et en suite, à la fin, pour le recyclage, tu as aussi pareil pour la consommation de l’électricité et de l’eau. Par conséquent, l'essentiel de la démarche green it qu'elle s'agit d'une  démarche globale. Effectivement,  tu ne peux pas focaliser sur une seule phase. Donc, la démarche green it c'est vraiment éco-concevoir un logiciel, tu dois aussi prendre le matériel…

Un site web qui est mal conçu, il est plus lourd, donc il fait plus de requêtes, il est trop gros, donc, il va utiliser pour le même résultat  plus d'énergie et le matériel va s'user plus vite... c'est toute une chaîne.

*Est-ce-que le matériel hardware a des impacts plus importants que le logiciel ?*

Oui le matériel a plus de poids que le site d’internet.

Par exemple, entre les terminaux (ordinateur), le réseau (web) et la date-center. Globalement, tu vois à part l'eau, effectivement, il y a le refroidissement la data center,  l'énergie que tu utilise pour les matériels, et le gaz à effet de serre que tu renvoie à cause de la production d’énergie, les ressource (matériaux) dont tu as besoin pour construire ton poste, en addition de la recyclage, tout ça c’est plus sur le matériel.

Ça ne veut pas dire que tu ne dois pas faire l’éco-conception pour un logiciel, mais que tu puisse le faire une fois que tu ad déjà assuré que tu as fait un poste bien éco-conception, cela ça veut dire qu’utiliser des matériaux recyclables, ou reprendre des postes anciens et reformater et réutiliser. Ça déjà tu peux le faire, et ensuite, en fait, une fois que tu as fait ça tu peux t'occuper de l'impact de ton logiciel.

Voilà, dans la manière générale, faire des pages simples est bénéfique pour l'utilisateur, ça devient plus lisible.

*Le Green IT est un sujet très intéressant mais compliqué à appliquer. Est-ce-qu le logiciel fait vieillir le matériel ?*

C’est plutôt le logiciel qui fait vieillir le matériel. Le logiciel a un impact sur le matériel. Un site mal conçu demande plus de ressources, donc, plus de dépense d’énergie, plus d’énergie nécessaire pour un gros site, va donc avoir un impact fait vieillir prématurément l’écran, le hardware, etc. Donc, c’est le logiciel qui a un impact sur le matériel.

*Qu'entendons-nous par "logiciel obèse" ?*

En théorie, un logiciel s'il a été bien conçu peut durer éternellement. Sauf après, s’il a été mal conçu, on dit qu’il est un logiciel obèse. Par exemple, un site web a été conçu d'abord sur ordinateur , et puis les commerciaux veulent qu'ils marchent aussi sur téléphone, donc ils rajoutent des lignes de code nécessaires, du poids, des requêtes et de ne pas optimiser le code, donc, au fer au mesure le logiciel va être plus en plus plus gros, plus compliqué ! Donc, tu oblige de repartir de zéro. 

Globalement un logiciel bien éco-conçu est simple et édifié avec des bonnes règles de codes.
