<<<
== Conclusion ///reste à faire///

Les travaux de ce mémoire ont enrichi mes connaissances et mes compétences dans le domaine du Green-IT, surtout que ce mémoire a été encadré par le département DSIT de la société RTE. Ce département a mis en place des procédures évolutives afin d'appliquer le concept du Green-IT, ce qui a ouvert l'opportunité d'approfondir mes recherches de ce sujet en milieu professionnel. La durabilité des logiciels est un sujet récent et et peu courant, et j’ai eu l’occasion de le traiter dans ce mémoire, malgré le fait qu’il y en a peu des études et des recherches scientifiques, ce qui a durci les travaux. 

Le but principal de ces travaux était de construire une matrice formant la base du future travail des ingénieurs cherchant à appliquer le Green-IT dans leur projets. La matrice a été construite grâce aux grandes efforts dépensées afin de grouper au maximum les critères susceptibles d’affecter la durabilité des logiciels. Des recherches profondes ont été réalisées afin de sélectionner soigneusement ces critères et de mieux contextualiser la problématique soulevée. 

La durabilité des logiciels est un domaine jeune nécessitant à être valorisé, ce qui pousse à mettre en place une bonne méthodologie avec ses méthodes pratiques, et de sensibiliser les futurs ingénieurs à prendre en compte l’importance de la bonne conception de leurs logiciels, et de les rendre respectueux de l’environnement. 
