<<<
== 8. Conclusion 

Les travaux de ce mémoire ont enrichi mes connaissances et mes compétences dans le domaine du Green-IT, surtout que ce mémoire a été encadré par le département DSIT de la société RTE. Ce département a mis en place des procédures évolutives afin d'appliquer le concept du Green-IT, ce qui a ouvert l'opportunité d'approfondir mes recherches de ce sujet en milieu professionnel. La durabilité des logiciels est un sujet récent et peu courant. J’ai eu l’occasion de le traiter dans ce mémoire, malgré la rarté des études et des recherches scientifiques dans la matière. 

Le but principal de ces travaux était de construire une matrice formant la base de futurs travaux des ingénieurs cherchant à appliquer le Green-IT dans leurs projets. La matrice de durabilité de logiciels a été majoritairement construite grâce aux interviews des acteurs industriels de RTE, ce qui a permis de grouper au maximum les critères susceptibles d’affecter la durabilité des logiciels.

La durabilité des logiciels est un domaine encore jeune nécessitant d'approfondissement et des demonstrations de sa valeur. Idéalement, ce travail pourrait contribuer à mettre en place une bonne méthodologie, simple dans la pratique, et de sensibiliser les futurs ingénieurs à prendre en compte l’importance de la bonne conception de leurs logiciels, et de les rendre respectueux de l’environnement. 
