:toc-title: Plan



include::Introduction.adoc[leveloffset=+1]
include::Méthodes-de-recherche.adoc[leveloffset=+1]
include::Etat-art.adoc[leveloffset=+1]
include::Enquetes-interviews.adoc[leveloffset=+1]
include::Matrice.adoc[leveloffset=+1]
include::Preconisation.adoc[leveloffset=+1]
include::Analyse-critique-et-travaux-ulterieur.adoc[leveloffset=+1]
include::Conclusion.adoc[leveloffset=+1]


<<<
[bibliography]
== Bibliographie 

- [[[A,1]]] Fabian Loeser. Technische Universitaet Berlin. Green IT and Green IS: Definition of Constructs and Overview of Current Practices.
Cité 67 fois researchgate.net 
https://www.researchgate.net/profile/Fabian_Loeser/publication/267737651_Green_IT_and_Green_IS_Definition_of_Constructs_and_Overview_of_Current_Practices_Completed_Research_Paper/links/5458cd700cf2cf516483bb66.pdf[L'article]

- [[[B,2]]] S Murugesan.  2008 - ieeexplore.ieee.org. Harnessing Green IT: Principles and Practices. Cité 1318 fois. 
https://www.pitt.edu/~dtipper/2011/GreenPaper.pdf[L'article]

- [[[C,3]]] LOI n° 2015-992 du 17 août 2015 relative à la transition énergétique pour la croissance verte (1). Article 99. legifrance.gouv.fr. 
https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=D07E4B7FF38C9264A5554513AB55B753.tplgfr22s_1?cidTexte=JORFTEXT000031044385&dateTexte=20200416[L'article]

- [[[D,4]]] Viktor C. Pavlu. 2003 – 2004. Thin-Client/Fat-Client Comparison. UNIVERSITY OF DERBY Derbyshire Business School. 
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.132.6689&rep=rep1&type=pdf[L'article]

- [[[E,5]]] Luca FALVO. 2016. Haute École de Gestion de Genève (HEG-GE). Développements Natif, Xamarin, Hybride ou Web : Critères de choix et arbre de décision pour
un développement mobile. 
https://doc.rero.ch/record/278092/files/TDIG_Falvo_Luca.pdf[L'article]

- [[[F,6]]] Frédéric Bordage. GreenIT.fr. 2019. Empreinte environnementale du numérique mondial.
https://www.greenit.fr/wp-content/uploads/2019/10/2019-10-GREENIT-etude_EENM-rapport-accessible.VF_.pdf[L'article]

- [[[G,7]]] Christophe BOUILLON, Michel HAVARD. Rapport d'information déposé en application de l'article 145 du Règlement par la mission d'information
sur la gestion durable des matières premières minérales. assemblee-nationale.fr
http://www.assemblee-nationale.fr/13/rap-info/i3880.asp[L'article]

- [[[H,8]]] Shailendra Mudgal, Benoît Tinetti, Thibault Faninger, Sarah Lockwood, Gina Anderson. Étude sur la durée de vie des équipements éléctriques et
éléctroniques. Juillet 2012. Agence de la transition écologique (ADEME). ademe.fr.
https://www.ademe.fr/sites/default/files/assets/documents/84636_duree_de_vie_des_eee.pdf[L'article]

- [[[I,9]]] Mohan MUNASINGHE, Osvaldo CANZIANI, Ogunlade DAVIDSON, Bert METZ, Martin PARRY, Mike Harrison. Integrating sustainable development and climate change in the IPCC fourth assessment report. 2003. 
https://archive.ipcc.ch/pdf/supporting-material/ipcc-4th-assessment-2003-03.pdf[L'article]

- [[[J,10]]] L'informatique émet plus de gaz à effet de serre que l'aviation.  21 octobre 2015
https://www.pourlascience.fr/sd/informatique/linformatique-emet-plus-de-gaz-a-effet-de-serre-que-laviation-8741.php[L'article]

- [[[K,11]]] Didier Buchs,Cycle de vie du logiciel. University of Geneva, 20 May 2014
https://www.researchgate.net/profile/Didier_Buchs/publication/37422534_Cycle_de_vie_du_logiciel/links/0fcfd5111030d47f2c000000.pdf[L'article]

- [[[L,12]]] L'informatique émet plus de gaz à effet de serre que l'aviation, 21 octobre 2015, 
https://www.pourlascience.fr/sd/informatique/linformatique-emet-plus-de-gaz-a-effet-de-serre-que-laviation-8741.php[L'article]

- [[[M,13]]] Quelle est l’empreinte carbone d’un ordinateur ?. site GreenIT.fr
https://www.greenit.fr/2011/02/10/quelle-est-l-empreinte-carbone-d-un-ordinateur/[L'article]

- [[[N,14]]] Candy Pang and Abram Hindle, University of Alberta, Bram Adams, Polytechnique Montréal, Ahmed E. Hassan, Queen’s University. What Do Programmers Know about Software Energy Consumption? IEEE Software, 2015 - ieeexplore.ieee.org.  Cité 85 fois.
https://ieeexplore.ieee.org/document/7155416[L'article]

- [[[O,15]]] Byung-Chul Choi, Hang-Sik Shin, Su-Yol Lee, Tak Hur. Life Cycle Assessment of a Personal Computer and its Effective Recycling Rate. 
https://www.researchgate.net/profile/Su_Yol_Lee/publication/226388568_Life_Cycle_Assessment_of_a_Personal_Computer_and_its_Effective_Recycling_Rate_7_pp/links/554ff10908ae93634ec879ad.pdf[L'article]



* « Programme / Logiciel ou Application », synonymes ou non ?. Apsynet.fr. 
https://www.apsynet.fr/programme-logiciel-ou-application-synonymes-ou-non/[L'article]

* Différents types de logiciel d'application. Microordinateur.blogspot.com
http://microordinateurr.blogspot.com/2012/11/differents-types-de-logiciel-d.html[L'article]

* La norme CEI 62402 utilise le mot « obsolète » ???

* IT Explained: Serveurs : https://www.fr.paessler.com/it-explained/server

// mettre le lien pour le moteur de recherche l'impact facteur
