:imagesdir: ./images 
<<<

== Etude qualitative et quantitative

=== Etude qualitative : Interviews ///reste à faire///

Le choix des profils à interviewer a été basé sur des personnes qui travaillent dans le département R&D de RTE, et des personnes qui sont des experts GreenIT dans le département DSIT.

Étant dans une phase d'état de l'art, les questions posées étaient aussi ouvertes que possible afin de favoriser la collecte d'informations sans restreindre la personne interrogée. Les personnes interrogées n'ont pas eu accès aux questions au préalable afin d'obtenir les réponses les plus sincères possibles. Les premières questions portaient sur le concept de recherche scientifique et de GreenIT, mais aussi sur la définition de la durabilité des logiciels et les critères qui, selon eux, rendent les logiciels plus durables.

=== Etude quantitative : Présentation du questionnaire

Comme ce travail est chargé de construire la matrice de durabilité, un questionnaire a été réalisé afin de recueillir les critères qui rendent les logiciels plus durables ou non selon les développeurs.

Deux questionnaires ont été menés, l’un en français et l’autre en anglais. Ce dernier comprend deux sections principales. La première fournit des informations sur les années d’expérience des répondants et les langages de programmation. Elle permet également de savoir si les répondants sont des développeurs d’applications pour smartphones ou non. Car ce questionnaire s’adressait d’abord aux développeurs de smartphones, et ensuite à tous les développeurs.

La deuxième me permet de savoir si les développeurs tiennent compte de la consommation d'énergie, et de recueillir les critères qui me permettent de construire la matrice de durabilité. En outre, cette partie comprend deux questions ouvertes destinées aux développeurs pour leur permettre de suggérer des moyens d'évaluer la durabilité des logiciels et des méthodes de conception technique.

Les résultats ont montré que les développeurs avaient différents niveaux d'expérience avec une représentation plus élevée de plus de 10 ans et de 3 à 5 ans d'expérience. En outre, les langages de programmation les plus utilisés sont : Java, C++ et Python, avec une représentation plus faible de : Objective C, Swift et KotLin.

La différence de niveau d'expérience des développeurs me permet d'observer que les participants n'ont pas la même expérience de la manière dont le logiciel consomme les ressources de la machine et, par conséquent, la conscience de la consommation d'énergie. Ceci est également confirmé par les résultats de la quatrième question : *Tenez-vous compte de la consommation d'énergie lors du développement de logiciels ? Si oui, comment comptabilisez-vous la consommation d'énergie ?*.  

La plupart des réponses à la quatrième question étaient : 

* "Non, malheureusement"
* "La performance est recherchée, donc rapidité des calculs en réduisant au maximum la complexité des développements ce qui peut alléger la mémoire ou le CPU parfois mais aucune mesure durable n'est mise en place pour vérifier que cela induit un réduction de consommation d'énergie"
* "Parfois, quand on s'apperçoit qu'il y a un consommation anormale visible à l'utilisation de l'application ex ( le smartphone se décharge rapidement avec une utilisation prolongée, des messages de l'os du téléphone qui l'indique clairement ...)"
* "Parfois, quand on s'apperçoit qu'il y a un consommation anormale visible à l'utilisation de l'application ex ( le smartphone se décharge rapidement avec une utilisation prolongée, des messages de l'os du téléphone qui l'indique clairement ...)"

Par conséquent, les développeurs ne prennent presque jamais en compte la consommation d'énergie, sauf si celle-ci est perceptible. Cela implique que les développeurs ne sont pas conscients de la consommation d'énergie des logiciels. Ceci est également confirmé, dans l'article <<P>> que j'ai détaillé dans le chapitre "État de l'art".

J'ai pu recueillir les critères de la matrice et les trier par importance en posant les deux questions suivantes :

* *Selon vous quels sont les critères qui rendent les applications/logiciel pour Smartphones plus durables ?*
* *Selon vous quels sont les critères qui font-vieillir les Smartphones ?*

En ce qui concerne les critères qui rendent les logiciels plus durables, les critères suivants sont de la plus haute importance :

* " Mise à jour de sécurité jointes aux mises à jour fonctionnelles. "
* " Lazy Loading. "
* " Développement Open source. "
* " Mode nuit / jour. "


En outre, les développeurs ont proposé des critères tels que :

* " Minimaliser les dépendances extérieures surtout open source, utiliser les derniers SDK de developpement ( dernier iOS, derniere version d'android studio) cela donne une durée de vie moyenne de 3 ans. "
* " Moins de « gadgets » , se concentrer sur les fonctionnalités réellement attendues. "
* " Ensemble minimal de fonctionnalités. Performances sur des appareils lents. " 

D'autre part, les critères suivants sont de la plus haute importance pour provoquer le renouvellement des terminaux : 

* " Impact fort sur l'utilisation de la batterie. "
* " Usage intensif du CPU. "
* " Usage intensif du Mémoire. "

Avec une représentation variable des critères suivants : 

* " Travaille en arrière plan. "
* " Lancer automatiquement au démarrage par défaut. "
* " Binaire qui prend de l’espace. "

En outre, les développeurs ont proposé des critères tels que :

* " Progrès des devices, et obsolescence programmée : Une application qui a été developpée il y 3 ans, et n'a pas été modifiée depuis, ne peut pas être installée sur les iPhone 11. Presque même problème sur android. "
* " Publicité ." 

Je détaillerai ces critères de la matrice séparément dans le chapitre <<Les clés de la durabilité de logiciels>>.

Les deux dernières questions étaient des questions ouvertes aux développeurs pour voir s'ils connaissent des moyens d'évaluer la durabilité, une conception technique qui favorise la durabilité des logiciels.  Ces réponses m'ont permis de constater que les développeurs ne connaissent pas les bonnes techniques de conception et de développement, ni les façons dont les logiciels endommagent le matériel. En outre, certaines entreprises ne tiennent pas compte de la conception et de la durabilité dans leurs stratégies.

*Identifiez-vous des moyens pour évaluer la durabilité des logiciels pour Smartphones (voire en dehors de cette seule plateforme) ?*

Quelques réponses à cette question :

* " Qu'un logiciel puisse fonctionner pendant au moins plusieurs années (plus que 2 ans) sur le même appareil sans que les mises à jour rendent le smartphone obsolète. "
* " Bonne gestion du mode offline / cache et synchronisation, Compatibilité des OS, Complexité fonctionnelles applicative. "
* " L'age du logiciel, les intervalles entre les maintenances/évolutions, l'évolution de son utilisation dans le temps (est-ce que le logiciel continue d'être utilisé après 2, 5, 10 ans..). "
* " Peut être pourrait on suivre la différence de consommation de batterie et d'usage de CPU pour un usage identique de l'application entre deux release? "
* " Capacité du logiciel a fonctionner sur des anciens modèles de smartphone. "

*Selon vous y-a-t-il des méthodologies de projet, de conception technique qui favorisent la durabilité des logiciels?*

Quelques réponses à cette question :

* " Il en existe certainement mais elles ne sont pas mises en avant au sein de mon entreprise et il n’y a aucune mention de la durabilité du logiciel dans le cahier des charges. "
* " Pas vraiment une méthodologie, mais l'optimisation des traitements (algorithme, nombre de requêtes en BD, ne remonter que les données nécessaires, ...) limitent la consommation. "
* " Les bonnes pratiques de développement visant à avoir un logiciel facilement maintenable favorisent aussi la durabilité je pense. Par contre si on veut mettre la durabilité comme objectif principal je pense que cela peut obliger à certains renoncements sur certaines fonctionnalités qui n’apportent pas un gain suffisant pour justifier leur fort coût en ressources par exemple. " 
* " Le low code, prendre des technos actuelles et stables, essayer de faire du code réutilisable dans d'autres fonctionnalités/projets. "

Pour le questionnaire et ses réponses, voir l'annexe 5.
