:imagesdir: ./images 
<<<

== Etude qualitative et quantitative

=== Etude qualitative : Interviews ///reste à faire///

Le choix des profils à interviewer a été basé sur des personnes qui travaillent dans le département R&D de RTE, et des personnes qui sont des experts GreenIT dans le département DSIT.

Étant dans une phase d'état de l'art, les questions posées étaient aussi ouvertes que possible afin de favoriser la collecte d'informations sans restreindre la personne interrogée. Les personnes interrogées n'ont pas eu accès aux questions au préalable afin d'obtenir les réponses les plus sincères possibles. Les premières questions portaient sur le concept de recherche scientifique et de GreenIT, mais aussi sur la définition de la durabilité des logiciels et les critères qui, selon eux, rendent les logiciels plus durables.

=== Etude quantitative : Présentation du questionnaire

Un questionnaire a été réalisé afin de recueillir les critères qui rendent les logiciels plus durables ou non.

Deux questionnaires ont été menés, l'un en français et l'autre en anglais.

Ce dernier comprend deux sections principales. La première fournit des informations sur les années d'expérience des répondants et les langages de programmation. Elle permet également de savoir si les répondants sont des développeurs d'applications pour smartphones ou non. Car ce questionnaire s'adressait d'abord aux développeurs de smartphones, et ensuite à tous les développeurs.

La deuxième me permet de savoir si les développeurs prennent en compte la consommation d'énergie, et de recueillir les critères qui me permettent de construire la matrice de durabilité. Cette partie comprenait deux questions ouvertes pour que les développeurs puissent proposer des moyens d'évaluer la durabilité des logiciels et les méthodologies de conception technique.

