<<<
== 2.Méthodologie de recherche

Afin d'aborder la problématique de ce mémoire, et de confirmer ou d'infirmer les hypothèses ci-dessous, cette étude est composée de trois phases (l'état de l'art, les études qualitatives et quantitatives, la construction de la matrice de durabilité du logiciel) que je détaillerai plus tard.

Chaque phase du cycle de vie des terminaux, depuis leur fabrication jusqu'à leur destruction ou leur recyclage, a un impact sur l'environnement. C'est pourquoi Green IT est chargé d'étudier chaque phase séparément et de trouver des solutions plus durables.

Pour aboutir à une problématique je me suis posée les questions qui suivent:

1. Les terminaux ont-ils plus d'impact sur l'environnement que les logiciels, ou le contraire ? 
2. Le logiciel entraîne-t-il le renouvellement des terminaux ?
3. Les logiciels ont-ils un impact direct sur l'environnement ? 
4. Les logiciels peuvent-ils être rendus plus durables ?

J'essayerai de répondre à ces questions avec les hypothèses suivantes.

Et comme expliqué dans l'hypothèse 3, les logiciels n'ont pas d'impact direct sur l'environnement, mais leurs impacts sont sur les terminaux. J'ai donc décidé de faire une étude sur le cycle de vie des logiciels et sur la manière dont les logiciels entraînent le renouvellement prématuré des terminaux. Comme je l'ai mentionné dans l'introduction, il existe plusieurs familles de logiciels, j'ai donc choisi la famille des logiciels pour smartphones. 

*Le logiciel et son cycle de vie provoquent-ils le renouvellement prématuré des terminaux ?*

=== 2.1.Les hypothèses

==== 2.1.1._Hypothèse 1_ : *Le Hardware a un impact plus important que le Software sur l'environnement*

 
  "La plupart des chiffres disponibles aujourd’hui établissent que le numérique serait à l'origine de 3,7 % des émissions totales de gaz à effet de serre (GES) dans le monde en 2018 et de 4,2 % de la consommation mondiale d’énergie primaire. Au niveau mondial, 44 % de cette empreinte serait due à la fabrication des terminaux, des centres informatiques et des réseaux et 56 % à leur utilisation."
  
référence <<C>> 
  


Le cycle de vie d'un équipement comporte plusieurs étapes qui commencent par la préfabrication et se terminent par la fin de vie <<N>> Chaque étape a son propre impact sur l'environnement.

La phase de préfabrication a l'impact le plus élevé sur l'environnement car elle nécessite d'extraire des matériaux non recyclables et non renouvelables, suivie de la phase d'utilisation [<<N>>, figure 2 page 125]. Cette dernière a un impact sur l'environnement notamment du fait de la consommation d'énergie induite. Pour aller plus loin, je détaille chaque étape du cycle de vie d'un équipement informatique et les impacts pour chaque phase dans le chapitre <<L\'importance du couplage entre Software et Hardware>>.

 
====  2.1.2._Hypothèse 2_ : *Le Software peut entraîner "renouvellement" le Hardware*

Je considère à l'issue de ce travail de recherche que les logiciels peuvent provoquer le renouvellement prématuré des terminaux. Cela se présente sous plusieurs formes. Je pense à la demande disproportionnée de ressources machines (du fait d'une mauvaise conception et/ou développement logiciel.le), à l'impact des logiciels et des sollicitations des périphériques matériels associés (à mauvais escient) ou à une contribution à l'obsolence programmée (i.e. : de manière mercantile en l'occurrence).

En regard de cette hypothèse, je propose la matrice de durabilité présentée au chapitre <<Matrice>>. Elle présente les critères detérminants en termes de durabilité logicielle.


====  2.1.3._Hypothèse 3_ : *Le service numérique a un impact sur l'environnement*
 
Considérant une population moyenne d'un pays développé et son inconscient collectif, il est important de savoir que les logiciels, de part leur absence d'existence physique, n'auraient aucun impact direct sur l'environnement. Pour démontrer l'inverse, il suffit de rappeler que le matériel stocke de l'information (disque dur, clé USB), fait fonctionner et les logiciels qui opèrent des calculs pour rendre des services (processeurs, mémoire, etc.). Ces éléments ont, à chaque étape de leur cycle de vie, bel et bien un impact sur l'environnement. Par conséquent, pour accepter cette hypothèse ou la rejeter nous devons mesurer l'influence des logiciels afin déterminer leur impact sur les matériels sous jaccents et donc les impacts environnementaux.


====  2.1.4._Hypothèse 4_ : *On peut améliorer la durabilité des logiciels*

La durabilité logicielle, sans être définie, peut être lue de prime abord comme un oxymore. En effet, le turn over des technologies, des matériels, etc. est de nos jours tel qu'il peut sembler vain de vouloir rendre durable un logiciel. D'une part la définition faite au sein du chapitre <<Principes et Définitions >> porte plus sur l'impact environnemental que d'un objectif de faire durer un logiciel sur la longueur. D'autre part, le paragraphe illustration <<Enquête et interviews >> propose de démontrer par la pratique qu'il est possible de mal concevoir un logiciel, de mal le développer, de mal l'utiliser et de laisser une empreinte résiduelle forte à la suppression. Par opposition directe il est évidemment possible de bien faire  sur chaque étape du cycle de vie. La matrice de durabilité permet d'identifier les critères significatifs pour ce faire.


=== 2.2.Les phases

=== 2.2.1.PHASE 1 l’état de l’art 

La première concerne un état de l’art : une revue littéraire succincte a été réalisée afin de rassembler tous les modèles et caractéristiques des études précédentes. Cette revue se concentre sur les études qui illustrent certains concepts liés à la durabilité, d'une part, et au cycle de vie d'un matériel informatique et d'un logiciel et à leurs impacts sur l'environnement, d'autre part. En effet, il est nécessaire de comprendre la notion de durabilité et l'empreinte environnementale du matériel informatique afin de construire la matrice de durabilité des logiciels. Pour ce faire, des recherches ont été effectuées sur Google Schoolar avec les mots clés suivants GreenIT, durabilité, cycle de vie, matériel, logiciel, empreinte environnementale. Les mots clés ont également été recherchés en anglais : GreenIT, sustainability, product lifecycle, computing equipment, software, environment impact, afin d'obtenir le plus de résultats possible. Les études retenues ont été celles qui ont été le plus de fois citées dans d’autres publications.

=== 2.2.2.PHASE 2 les études qualitatives et quantitatives 

La deuxième phase de cette étude consiste, dans un premier temps, en des entretiens avec sept personnes ayant des expériences différentes (chercheurs en R&D, experts GreenIt) dans l'entreprise où j'ai fait mon apprentissage. Ces entretiens ont été réalisés pour définir, selon les experts, la notion de durabilité des logiciels, mais aussi pour savoir quels sont les critères qui rendent les applications/logiciels plus durables.

Dans un deuxième temps, j'ai publié un questionnaire réalisé avec l'outil Google Form et diffusé sur le réseau professionnel LinkedIn sous forme de post puis en le partageant avec mon entourage en France, en Allemagne et en Jordanie. La collecte des réponses a permis à cette étude de faire une analyse afin de construire la matrice de durabilité pour répondre à la problématique.

=== 2.2.3.PHASE 3 construire la matrice de durabilité des logiciels

Enfin, la dernière phase correspond à l'analyse des réponses aux questionnaires et aux entretiens afin de trouver les critères de durabilité. L'objectif de cette analyse est de construire une matrice qui donne un score à un logiciel en indiquant sa note de durabilité.
