<<< 
== Remerciements

Le succès de la réalisation des espoirs souhaités est un rêve atteignable en déponsant des grands efforts, et surtout en ayant un entourage prêt à consacrer tous ses efforts et ses expériences.

À cet égard, je me tiens à remercier toutes les personnes qui ont contribué au succès de mon projet professionnel et qui m’ont aidée lors de la rédaction de ce mémoire.

Pas plus beau que je débute à remercier ma tuturice de mémoire Mme. Rebecca DENECKERE, professeur de MIAGE à l’université de Panthéon Sorbonne Paris1, pour sa patience, sa disponibilité et surtout ses judicieux conseils, qui ont contribué à alimenter ma réflexion.

Je remercie également toute l’équipe pédagogique de l’université de Panthéon Sorbonne Paris1.
 
Je me trouve sans aucun mot exprimant ma gratitude pour ma grande famille RTE. Cette famille m'a toujours traité comme sa fille, et m'a concédé tout le soin et l'attention. Leur comportement chaleureux a rendu mon expérience, chez eux, innoubliable. 

Je tiens à témoigner toute ma reconnaissance aux personnes suivantes, pour leur aide dans la réalisation de ce mémoire:

M. Boris DOLLEY qui m’a beaucoup aidé, en partageant ses connaissances et expériences, tout en m’accordant sa confiance et une large indépendance dans l’exécution de mes missions valorisantes.

M. Marc VILLEMON, M. Baptiste LETELLIER, M. Vincent BARBASENT, M. Rémy CLÉMENT et M. Jean-Marc DEBRAYME pour leur générosité en me consacrant du temps afin de réaliser des interviews riches en informations et expériences personnelles.

 M. Nathaël GALANTE-GRAS, le chef de projet "Éco2mix", qui m'a accompagné avec grand plaisir tout au long du test éffectué sur ce projet, et qui m'a concédé ses conseills précieux.

Mme. Hanae SAFI et Mme. Alexandra GUIRONNET, mes supportrices, pour leur soutien dans l’élaboration de ce mémoire.

Les joilis mots partant du cœur, portent toute ma reconnaissance et ma gratitude, et bien sûr mon remerciement à mes amies, Sarah, Charlotte et Hamel, pour leur temps dédié à relire mon mémoire.

À la fin, toutes mes sensations se rassamblent à remercier l'oasis chaleureuse dans ma vie, la famille agréable, mes parents, ma sœur et mes frères , pour leur soutien constant et leurs encouragements.
