<<< 
= Remerciements

Le succès de la réalisation des espoirs souhaités est un rêve atteignable en dépensant des grands efforts, et surtout en ayant un entourage prêt à consacrer tous ses efforts et ses expériences.

À cet égard, je tiens à remercier toutes les personnes qui ont contribué à la réalisation de mon projet professionnel et qui m’ont aidé lors de la rédaction de ce mémoire.

Mes premiers remerciements sont destinés à ma tutrice de mémoire Madame Rebecca DENECKERE, professeur de MIAGE à l’université de Panthéon Sorbonne Paris1. Je l'a remercie pour sa patience, sa disponibilité et surtout ses judicieux conseils, qui ont contribué à alimenter ma réflexion.

Je remercie également toute l’équipe pédagogique de l’université de Panthéon Sorbonne Paris1.
 
Les mots me manquent pour exprimer ma gratitude envers la grande famille que représente RTE "Réseau de Transport d'Électricité", l'entreprise qui m'a accueillie durant ce stage. Cette famille m'a toujours traitée comme sa fille, et m'a concédé tout le soin et l'attention. Leur comportement chaleureux a rendu mon expérience, chez eux, inoubliable. 

Je tiens à témoigner toute ma reconnaissance aux personnes suivantes, pour leur aide dans la réalisation de ce mémoire : 

Monsieur Boris DOLLEY, mon tuteur chez RTE, à qui j'adresse ma plus grande reconnaissance et ma gratitude pour son aide. Dès le début, il m'a partagé ses connaissances, expériences et m'a accordé sa confiance tout en me laissant une large indépendance dans l'exécution de mes missions.

Monsieur Marc VILLEMON, Monsieur Baptiste LETELLIER, Monsieur Vincent BARBASENT, Monsieur Rémy CLÉMENT et Monsieur Jean-Marc DEBRAYME pour leur générosité en me consacrant du temps afin de réaliser des interviews riches en informations et expériences personnelles.

Monsieur Nathaël GALANTE-GRAS, le chef de projet "Éco2mix", qui m'a accompagné avec grand plaisir tout au long du test effectué sur ce projet, et qui m'a concédé ses conseils précieux. 

Madame Hanae SAFI et Madame Alexandra GUIRONNET, mes supportrices, pour leur soutien dans l’élaboration de ce mémoire.

Merci à ma famille, mes proches, pour leur soutient constant, leurs encouragements et le temps qu'ils ont consacré à la relecture de mon Mémoire.
